[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Reduce function size by excluding unnecessary files
  excluded_patterns = [
    "node_modules/@solana/web3.js/lib/esm/**",
    "node_modules/@metaplex-foundation/**/esm/**",
    "**/*.map",
    "**/*.d.ts"
  ]
  
  # Set function timeout
  timeout = 30

# Headers for caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
